#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rubber:
  proxy:
    config:
      db-instances:
        at_tennis_db:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.26.108.182:3306/at_tennis?useUnicode=true&characterEncoding=utf8
          username: root
          password: JTg7yyAe
